---
- name: Creation des dossiers de backup distant avec les permissions
  hosts: web1:web2:bdd1:bdd2
  become: yes
  tasks:
    - name: Creation du dossier /backup
      file:
        path: "/backup"
        state: directory
        mode: '0755'

    - name: Don des permissions lecture ecriture a l'utilisateur postgres dans le dossier backup pour les BDD
      file:
        path:
        owner: postgres
        group: postgres
        mode: '0777'
      when: inventory_hostname in ['bdd1', 'bdd2']

