---
- name: Installer et configurer node_exporter
  hosts: all
  become: yes
  tasks:
    - name: Telecharger node exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter.tar.gz"

    - name: Extraire les fichiers de node exporter
      unarchive:
        src: "/tmp/node_exporter.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Deplacer l'executable jusqua /usr/local/bin
      command: "mv /tmp/node_exporter-1.5.0.linux-amd64/node_exporter /usr/local/bin"
      args:
        creates: "/usr/local/bin/node_exporter"

    - name: Creer le groupe node_exporter
      group:
        name: node_exporter
        system: yes

    - name: Ajouter l'utilisateur node_exporter
      user:
        name: node_exporter
        group: node_exporter
        shell: /bin/false

    - name: Deplacer le fichier de service node exporter
      template:
        src: templates/node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service

    - name: ajouter droits execution sur le fichier de service node exporter
      command: "chmod +x /etc/systemd/system/node_exporter.service"

    - name: Demarrer le fichier de service node exporter
      command: "/usr/local/bin/node_exporter"
